### ISSUE TITLE
Event conversion FAQ

### ISSUE THREAD

**Issue by chalemic** [omfgtora/Idle-Champions-FAQ#63] opened 2018-04-17 15:02 UTC
Every event there are new players asking whether or not to reset their blessings prior to favor conversion. It would be helpful to have a FAQ entry addressing this question.

Q: Should I reset my blessings before converting event favor (favour)?

A: No, resetting your blessings is not necessary. The conversion is based on your total favor earned in the campaign, so it includes the favor spent on blessings.

**Comment by PJP2810** [comment] 2018-04-17 21:33
Thank you for this submission. Marked as duplicate of https://github.com/omfgtora/Idle-Champions-FAQ/issues/51

**Closed** 2018-04-17 21:34 UTC
Labels: duplicate
